function(enable_lto)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT outuput)
    if(result)
        message(STATUS "Using LTO/IPO")
        set_property(GLOBAL PROPERTY INTERPROCEDURAL_OPTIMIZATION)
    else()
        message(WARNING "LTO/IPO is not supported by your compiler.")
    endif()
endfunction()