function(add_sanitizer_flags)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "CLANG")
        add_compile_options("-fno-omit-frame-pointer")
        add_link_options("-fno-omit-frame-pointer")
        if(ENABLE_SANITIZE_ADDRESS)
            add_compile_options("-fsanitize=address")   #These might not be supported by gcc on Windows
            add_link_options("-fsanitize=address")
        endif()
        if(ENABLE_SANITIZE_UB)
            add_compile_options("-fsanitize=undefined")
            add_link_options("-fsanitize=undefined")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if(ENABLE_SANITIZE_ADDRESS)
            add_compile_options("/fsanitize=address")
        endif()
        if(ENABLE_SANITIZE_UB)
            message(STATUS "Undefined sanitizer not implemented on MSVC")
        endif()
    else()
        message(WARNING "This auto sanitizer doesn't support your compiler, add flags manually.")
    endif()
endfunction()